spring:
  kafka:
    producer:
      bootstrap-servers:
        -localhost:9092

      groupId: jt-group-1

    consumer:
      group-id: tpd-logger
      auto-offset-reset: earliest
      bootstrap-server:
        -localhost:9092
      topic-name: advice-topic
      message-per-request: 10